version: 2
jobs:
    # The build job
    build:
        working_directory: ~/DialogflowAgentFulfillment
        docker:
            - image: circleci/node:8.0-browsers
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                paths:
                - test
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: npm install
            # Cache local dependencies if they don't exist
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            # Test the bot conversations
            - run:
                name: Testing bot conversations
                command: cd test && yarn install && npm run test
            # Test the Firebase fulfillment
            - run:
                name: Testing Firebase fulfillment
                command: cd firebaseFulfillment/firebase/functions && yarn install && npm run test
